server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: second-api
          uri: http://localhost:8083/
          predicates:
            - Path=/second-api/**
        - id: first-api
          uri: http://localhost:8082/
          predicates:
            - Path=/first-api/**
